services:
- type: web
  name: reimed-whatsapp-backend
  env: node
  plan: free
  buildCommand: "npm install"
  startCommand: "node server.mjs"
  autoDeploy: true
  envVars:
  - key: WHATSAPP_ACCESS_TOKEN
    sync: false
  - key: WA_PHONE_NUMBER_ID
    sync: false
  - key: WHATSAPP_VERIFY_TOKEN
    sync: false
  - key: WHATSAPP_GRAPH_BASE
    value: https://graph.facebook.com
  - key: WHATSAPP_GRAPH_VERSION
    value: v20.0
  - key: ALLOWED_ORIGINS
    value: https://reimed-whatsapp-frontend.netlify.app
